route:
    group_by: ['alertname']
    group_interval: 30s
    repeat_interval: 1h
    group_wait: 30s
    receiver: 'prometheus-msteams'

receivers:
    - name: 'prometheus-msteams'
      webhook_configs:
      - send_resolved: true
          url: 'http://192.168.3.105:9093/alertmanager' # the prometheus-msteams proxy
