global:
    scrape_interval: 15s
    external_labels:
        monitor: 'my-monitor'

# this is where we have alert rules
rule_files:
    - /etc/prometheus/alert.rules.yml

# A scrape configuration 
scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']

    # Node-exporter scraper
    - job_name: 'node_exporter'
      scrape_interval: 10s
      static_configs:
# Add all ip addresses that you will watch with node-exporter
        - targets:
          #- 192.168.3.101:9100
          #- 192.168.3.102:9100
          #- 192.168.3.103:9100
          - 192.168.3.104:9100


    # Kubestate metrics scraper: there should be kube-state-metrics installation on the target cluster
    - job_name: 'kube-state-metrics'
      scrape_interval: 30s
      static_configs:
        - targets: ['192.168.3.101:30080']

    - job_name: 'kube-state-metrics_phoenix'
      scrape_interval: 30s
      static_configs:
        - targets: ['192.168.1.60:30000']

    # OpenTelemetry collector scraper
    - job_name: 'otel-collector'
      scrape_interval: 10s
      static_configs:
        - targets: ['otel-collector:8889']
        - targets: ['otel-collector:8888']        

# Alerting specifies settings related to the Alertmanager
alerting:
    alertmanagers:
        - static_configs:
          - targets: 
            - 192.168.3.105:9093
